[build]
  base = "Frontend_Projects/Smart_DashBoard_Panel"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/Frontend Projects/Smart_DashBoard_Panel/dist/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/Frontend_Projects/Smart_DashBoard_Panel/dist/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
